package org.openscore.clubs

import org.openscore.model.Sport
import org.openscore.model.Sport.BASEBALL
import org.openscore.model.Sport.FLOORBALL
import org.openscore.model.Sport.FOOTBALL
import org.openscore.model.Sport.HOCKEY

/**
 * The club crosswalk. One line per club; a club that plays in several of our leagues lists
 * every native id on that one line (Frölunda: SHL + CHL, Manchester United: Premier League +
 * UEFA, Hammarby: Sportomedia + Fogis). Grouped by the league the club is at home in; clubs
 * that only reach us through a cross-border competition come last.
 *
 * Slug rules: the club's own name, ASCII-folded, without legal or sponsor suffixes
 * (`hacken`, `frolunda`, `bayern-munchen`) unless the suffix is how the club is said
 * (`malmo-ff`, `paris-fc`, `hv71`). Where a football and a hockey club share a name the
 * hockey one carries `-hockey` (`djurgarden` / `djurgarden-hockey`). A slug is never reused
 * or renamed once published: a club that renames itself keeps its slug and gets a new [Club.name].
 *
 * `hockeyallsvenskan` ids are the league site's StatNet codes (`MODO`, `OSIK`), which replaced
 * the platform-wide Sportality uuids when it left that platform; a club that also plays in the
 * SHL keeps both ids.
 *
 * Id namespaces are league ids; `ucl` also covers `uel`/`uecl`, and `fogis` covers `allsvenskan`,
 * `superettan` and `svenska-cupen` (the Swedish leagues carry Fogis team ids) — see
 * [Clubs.namespace]. `efl` is the Gamechanger team id (`t43`) behind `championship` and
 * `carabao-cup`: every English club has one, so a Premier League line carries it next to its
 * Pulselive id (the same Opta number without the `t`, paired here by hand, never derived). `sportomedia` is the abbreviation allsvenskan.se keys its tables and squads
 * by; the feed's own `fogisId` bridge is verified against these lines by `ClubsCoverageLiveTest`,
 * which also prints new qualifiers as ready-to-paste lines. `espn` is ESPN's team id, carried
 * only by clubs whose squad comes from ESPN (the Bundesliga and the UEFA entrants without a
 * covered domestic league — see apis/football/espn) and hand-checked against ESPN's team
 * directories, never matched by name.
 *
 * Harvested from the live standings on 2026-09-13 (SHL/HockeyAllsvenskan from the September schedule).
 */
internal object ClubTable {

    private fun club(id: String, name: String, sport: Sport, country: String?, vararg ids: Pair<String, String>): Club =
        Club(id, name, sport, country, ids.toMap())

    val clubs: List<Club> = listOf(
        // ── NHL ──────────────────────────────────────────────────────────────────────────
        club("anaheim-ducks", "Anaheim Ducks", HOCKEY, "USA", "nhl" to "ANA"),
        club("boston-bruins", "Boston Bruins", HOCKEY, "USA", "nhl" to "BOS"),
        club("buffalo-sabres", "Buffalo Sabres", HOCKEY, "USA", "nhl" to "BUF"),
        club("calgary-flames", "Calgary Flames", HOCKEY, "CAN", "nhl" to "CGY"),
        club("carolina-hurricanes", "Carolina Hurricanes", HOCKEY, "USA", "nhl" to "CAR"),
        club("chicago-blackhawks", "Chicago Blackhawks", HOCKEY, "USA", "nhl" to "CHI"),
        club("colorado-avalanche", "Colorado Avalanche", HOCKEY, "USA", "nhl" to "COL"),
        club("columbus-blue-jackets", "Columbus Blue Jackets", HOCKEY, "USA", "nhl" to "CBJ"),
        club("dallas-stars", "Dallas Stars", HOCKEY, "USA", "nhl" to "DAL"),
        club("detroit-red-wings", "Detroit Red Wings", HOCKEY, "USA", "nhl" to "DET"),
        club("edmonton-oilers", "Edmonton Oilers", HOCKEY, "CAN", "nhl" to "EDM"),
        club("florida-panthers", "Florida Panthers", HOCKEY, "USA", "nhl" to "FLA"),
        club("los-angeles-kings", "Los Angeles Kings", HOCKEY, "USA", "nhl" to "LAK"),
        club("minnesota-wild", "Minnesota Wild", HOCKEY, "USA", "nhl" to "MIN"),
        club("montreal-canadiens", "Montréal Canadiens", HOCKEY, "CAN", "nhl" to "MTL"),
        club("nashville-predators", "Nashville Predators", HOCKEY, "USA", "nhl" to "NSH"),
        club("new-jersey-devils", "New Jersey Devils", HOCKEY, "USA", "nhl" to "NJD"),
        club("new-york-islanders", "New York Islanders", HOCKEY, "USA", "nhl" to "NYI"),
        club("new-york-rangers", "New York Rangers", HOCKEY, "USA", "nhl" to "NYR"),
        club("ottawa-senators", "Ottawa Senators", HOCKEY, "CAN", "nhl" to "OTT"),
        club("philadelphia-flyers", "Philadelphia Flyers", HOCKEY, "USA", "nhl" to "PHI"),
        club("pittsburgh-penguins", "Pittsburgh Penguins", HOCKEY, "USA", "nhl" to "PIT"),
        club("san-jose-sharks", "San Jose Sharks", HOCKEY, "USA", "nhl" to "SJS"),
        club("seattle-kraken", "Seattle Kraken", HOCKEY, "USA", "nhl" to "SEA"),
        club("st-louis-blues", "St. Louis Blues", HOCKEY, "USA", "nhl" to "STL"),
        club("tampa-bay-lightning", "Tampa Bay Lightning", HOCKEY, "USA", "nhl" to "TBL"),
        club("toronto-maple-leafs", "Toronto Maple Leafs", HOCKEY, "CAN", "nhl" to "TOR"),
        club("utah-mammoth", "Utah Mammoth", HOCKEY, "USA", "nhl" to "UTA"),
        club("vancouver-canucks", "Vancouver Canucks", HOCKEY, "CAN", "nhl" to "VAN"),
        club("vegas-golden-knights", "Vegas Golden Knights", HOCKEY, "USA", "nhl" to "VGK"),
        club("washington-capitals", "Washington Capitals", HOCKEY, "USA", "nhl" to "WSH"),
        club("winnipeg-jets", "Winnipeg Jets", HOCKEY, "CAN", "nhl" to "WPG"),

        // ── SHL / HockeyAllsvenskan (one Sportality id space; CHL ids where they qualified) ──
        club("bjorkloven", "Björklöven", HOCKEY, "SWE", "shl" to "4519-4519Rdei6"),
        club("brynas", "Brynäs", HOCKEY, "SWE", "shl" to "1ab8-1ab8bfj7N"),
        club("djurgarden-hockey", "Djurgården Hockey", HOCKEY, "SWE", "shl" to "2459-2459QTs1f"),
        club("farjestad", "Färjestad", HOCKEY, "SWE", "shl" to "752c-752c12zB7Z"),
        club("frolunda", "Frölunda", HOCKEY, "SWE", "shl" to "087a-087aTQv9u", "chl" to "ba55abe823bed83d7c12e7b3"),
        club("hv71", "HV71", HOCKEY, "SWE", "shl" to "3db0-3db09jXTE"),
        club("linkoping", "Linköping", HOCKEY, "SWE", "shl" to "41c4-41c4BiYZU"),
        club("lulea", "Luleå", HOCKEY, "SWE", "shl" to "1a71-1a71gTHKh"),
        club("malmo-redhawks", "Malmö Redhawks", HOCKEY, "SWE", "shl" to "8e6f-8e6fUXJvi"),
        club("orebro-hockey", "Örebro Hockey", HOCKEY, "SWE", "shl" to "82eb-82ebmgaJ8"),
        club("rogle", "Rögle", HOCKEY, "SWE", "shl" to "ee93-ee93uy4oW", "chl" to "47cce95deef579332978edc7"),
        club("skelleftea", "Skellefteå", HOCKEY, "SWE", "shl" to "50e6-50e6DYeWM", "chl" to "73caaf27776183ec10ea6ddc"),
        club("timra", "Timrå", HOCKEY, "SWE", "shl" to "31d1-31d1NbSlR"),
        club("vaxjo-lakers", "Växjö Lakers", HOCKEY, "SWE", "shl" to "fe02-fe02mf1FN", "chl" to "59b68db03ae141bf08f49775"),
        club("aik-hockey", "AIK Hockey", HOCKEY, "SWE", "shl" to "f7c8-f7c8isEb3", "hockeyallsvenskan" to "AIK"),
        club("almtuna", "Almtuna", HOCKEY, "SWE", "shl" to "181c-181cv0b9i", "hockeyallsvenskan" to "AIS"),
        club("bik-karlskoga", "BIK Karlskoga", HOCKEY, "SWE", "shl" to "1429-1429fuhHu", "hockeyallsvenskan" to "BIK"),
        club("kalmar-hc", "Kalmar HC", HOCKEY, "SWE", "shl" to "4b7a-cd81IIiWF", "hockeyallsvenskan" to "KHC"),
        club("leksand", "Leksand", HOCKEY, "SWE", "shl" to "9541-95418PpkP", "hockeyallsvenskan" to "LIF"),
        club("modo", "MoDo", HOCKEY, "SWE", "shl" to "110b-110bJcIAI", "hockeyallsvenskan" to "MODO"),
        club("mora", "Mora", HOCKEY, "SWE", "shl" to "dcba-dcbaXSrRU", "hockeyallsvenskan" to "MIK"),
        club("nybro-vikings", "Nybro Vikings", HOCKEY, "SWE", "shl" to "f32b-cd81wq7XN", "hockeyallsvenskan" to "NYB"),
        club("oskarshamn", "Oskarshamn", HOCKEY, "SWE", "shl" to "259b-259bYGVIp", "hockeyallsvenskan" to "IKO"),
        club("ostersund-hockey", "Östersund Hockey", HOCKEY, "SWE", "shl" to "4dbe-4dbeYflht", "hockeyallsvenskan" to "OSIK"),
        club("sodertalje", "Södertälje", HOCKEY, "SWE", "shl" to "936a-936aAY8bT", "hockeyallsvenskan" to "SSK"),
        club("vasteras-hockey", "Västerås Hockey", HOCKEY, "SWE", "shl" to "94ce-94ce8I8r", "hockeyallsvenskan" to "VIK"),
        club("vimmerby", "Vimmerby", HOCKEY, "SWE", "shl" to "d53c-cd81tOBRi", "hockeyallsvenskan" to "VHC"),
        club("visby-roma", "Visby/Roma", HOCKEY, "SWE", "shl" to "c699-c699vpXxF", "hockeyallsvenskan" to "VIS"),

        // ── Liiga ────────────────────────────────────────────────────────────────────────
        club("assat", "Ässät", HOCKEY, "FIN", "liiga" to "679171680"),
        club("hifk", "HIFK", HOCKEY, "FIN", "liiga" to "168761288"),
        club("hpk", "HPK", HOCKEY, "FIN", "liiga" to "55786244"),
        club("ilves", "Ilves", HOCKEY, "FIN", "liiga" to "951626834"),
        club("jokerit", "Jokerit", HOCKEY, "FIN", "liiga" to "238306801"),
        club("jukurit", "Jukurit", HOCKEY, "FIN", "liiga" to "292293444"),
        club("jyp", "JYP", HOCKEY, "FIN", "liiga" to "219244634"),
        club("k-espoo", "K-Espoo", HOCKEY, "FIN", "liiga" to "1368624751"),
        club("kalpa", "KalPa", HOCKEY, "FIN", "liiga" to "859884935"),
        club("karpat", "Kärpät", HOCKEY, "FIN", "liiga" to "495643563"),
        club("kookoo", "KooKoo", HOCKEY, "FIN", "liiga" to "461765763", "chl" to "c9840a203093f97cae0a9495"),
        club("lukko", "Lukko", HOCKEY, "FIN", "liiga" to "624554857"),
        club("pelicans", "Pelicans", HOCKEY, "FIN", "liiga" to "875886777"),
        club("saipa", "SaiPa", HOCKEY, "FIN", "liiga" to "933686567", "chl" to "6aa374572836df3fb42eb000"),
        club("sport", "Sport", HOCKEY, "FIN", "liiga" to "626537494"),
        club("tappara", "Tappara", HOCKEY, "FIN", "liiga" to "362185137", "chl" to "6a0612c54317b473a6f67f56"),
        club("tps", "TPS", HOCKEY, "FIN", "liiga" to "651304385"),

        // ── KHL ──────────────────────────────────────────────────────────────────────────
        club("admiral", "Admiral Vladivostok", HOCKEY, "RUS", "khl" to "61"),
        club("ak-bars", "Ak Bars Kazan", HOCKEY, "RUS", "khl" to "40"),
        club("amur", "Amur Khabarovsk", HOCKEY, "RUS", "khl" to "12"),
        club("avangard", "Avangard Omsk", HOCKEY, "RUS", "khl" to "10"),
        club("avtomobilist", "Avtomobilist Yekaterinburg", HOCKEY, "RUS", "khl" to "56"),
        club("barys", "Barys Astana", HOCKEY, "KAZ", "khl" to "46"),
        club("cska-moscow", "CSKA Moscow", HOCKEY, "RUS", "khl" to "16"),
        club("dinamo-minsk", "Dinamo Minsk", HOCKEY, "BLR", "khl" to "38"),
        club("dynamo-moscow", "Dynamo Moscow", HOCKEY, "RUS", "khl" to "8"),
        club("lada", "Lada Togliatti", HOCKEY, "RUS", "khl" to "105"),
        club("lokomotiv", "Lokomotiv Yaroslavl", HOCKEY, "RUS", "khl" to "26"),
        club("metallurg-magnitogorsk", "Metallurg Magnitogorsk", HOCKEY, "RUS", "khl" to "30"),
        club("neftekhimik", "Neftekhimik Nizhnekamsk", HOCKEY, "RUS", "khl" to "36"),
        club("salavat-yulaev", "Salavat Yulaev Ufa", HOCKEY, "RUS", "khl" to "32"),
        club("severstal", "Severstal Cherepovets", HOCKEY, "RUS", "khl" to "42"),
        club("shanghai-dragons", "Shanghai Dragons", HOCKEY, "CHN", "khl" to "315"),
        club("sibir", "Sibir Novosibirsk", HOCKEY, "RUS", "khl" to "24"),
        club("ska", "SKA Saint Petersburg", HOCKEY, "RUS", "khl" to "44"),
        club("sochi", "HC Sochi", HOCKEY, "RUS", "khl" to "113"),
        club("spartak-moscow", "Spartak Moscow", HOCKEY, "RUS", "khl" to "18"),
        club("torpedo", "Torpedo Nizhny Novgorod", HOCKEY, "RUS", "khl" to "22"),
        club("traktor", "Traktor Chelyabinsk", HOCKEY, "RUS", "khl" to "28"),

        // ── DEL (noc codes; CHL ids for this season's entrants) ──────────────────────────
        club("adler-mannheim", "Adler Mannheim", HOCKEY, "GER", "del" to "MAN", "chl" to "9bd414328e8c2658731938a0"),
        club("augsburger-panther", "Augsburger Panther", HOCKEY, "GER", "del" to "AEV"),
        club("eisbaren-berlin", "Eisbären Berlin", HOCKEY, "GER", "del" to "EBB", "chl" to "2e6ebca3b60eeec1da4b9e9b"),
        club("erc-ingolstadt", "ERC Ingolstadt", HOCKEY, "GER", "del" to "ING"),
        club("grizzlys-wolfsburg", "Grizzlys Wolfsburg", HOCKEY, "GER", "del" to "WOB"),
        club("iserlohn-roosters", "Iserlohn Roosters", HOCKEY, "GER", "del" to "IEC"),
        club("kolner-haie", "Kölner Haie", HOCKEY, "GER", "del" to "KEC", "chl" to "104c3b90fcb6da8e653c05eb"),
        club("krefeld-pinguine", "Krefeld Pinguine", HOCKEY, "GER", "del" to "KEV"),
        club("lowen-frankfurt", "Löwen Frankfurt", HOCKEY, "GER", "del" to "FRA"),
        club("nurnberg-ice-tigers", "Nürnberg Ice Tigers", HOCKEY, "GER", "del" to "NIT"),
        club("pinguins-bremerhaven", "Pinguins Bremerhaven", HOCKEY, "GER", "del" to "BHV"),
        club("red-bull-munchen", "EHC Red Bull München", HOCKEY, "GER", "del" to "RBM"),
        club("schwenninger-wild-wings", "Schwenninger Wild Wings", HOCKEY, "GER", "del" to "SWW"),
        club("straubing-tigers", "Straubing Tigers", HOCKEY, "GER", "del" to "STR"),

        // ── SSL Herr (Sportality team UUIDs) ─────────────────────────────────────────────
        club("aik-ibf", "AIK IBF", FLOORBALL, "SWE", "ssl" to "f7c8-49eaNieTr"),
        club("fbc-kalmarsund", "FBC Kalmarsund", FLOORBALL, "SWE", "ssl" to "4b7a-cd81hZAEl"),
        club("ibf-falun", "IBF Falun", FLOORBALL, "SWE", "ssl" to "e7cb-035exdeHN"),
        club("ibk-dalen", "IBK Dalen", FLOORBALL, "SWE", "ssl" to "e40a-781fGVFZV"),
        club("ibk-lund", "IBK Lund", FLOORBALL, "SWE", "ssl" to "ddfe-cd81c3YP1"),
        club("jonkopings-ik", "Jönköpings IK", FLOORBALL, "SWE", "ssl" to "5b11-cd81tVTqP"),
        club("linkoping-ibk", "Linköping IBK", FLOORBALL, "SWE", "ssl" to "90c3-21d6xSlWc"),
        club("mullsjo-ais", "Mullsjö AIS", FLOORBALL, "SWE", "ssl" to "2cdf-32c4bo2vU"),
        club("nykvarns-ibf", "Nykvarns IBF", FLOORBALL, "SWE", "ssl" to "5452-cd8111QiTe"),
        club("pixbo-ibk", "Pixbo IBK", FLOORBALL, "SWE", "ssl" to "8615-d492oYxBh"),
        club("storvreta-ibk", "Storvreta IBK", FLOORBALL, "SWE", "ssl" to "1c79-bb6dyljzt"),
        club("visby-ibk", "Visby IBK", FLOORBALL, "SWE", "ssl" to "c699-cd81gmNJ2"),
        club("vaxjo-vipers", "Växjö Vipers", FLOORBALL, "SWE", "ssl" to "a10c-6f9evklgz"),
        club("warberg-ic", "Warberg IC", FLOORBALL, "SWE", "ssl" to "c437-b283ovsh6"),

        // ── F-Liiga Men (TorneoPal club ids, which outlive a season's team registration) ──
        club("classic", "SC Classic", FLOORBALL, "FIN", "f-liiga" to "486"),
        club("eraviikingit", "EräViikingit", FLOORBALL, "FIN", "f-liiga" to "49"),
        club("esport-oilers", "Esport Oilers", FLOORBALL, "FIN", "f-liiga" to "56"),
        club("hawks", "Hawks", FLOORBALL, "FIN", "f-liiga" to "598"),
        club("jymy", "Jymy", FLOORBALL, "FIN", "f-liiga" to "4464"),
        club("lasb", "LASB", FLOORBALL, "FIN", "f-liiga" to "302"),
        club("nokian-krp", "Nokian KrP", FLOORBALL, "FIN", "f-liiga" to "374"),
        club("o2-jyvaskyla", "O2-Jyväskylä", FLOORBALL, "FIN", "f-liiga" to "384"),
        club("ols", "OLS", FLOORBALL, "FIN", "f-liiga" to "393"),
        club("spv", "SPV", FLOORBALL, "FIN", "f-liiga" to "622"),
        // The hockey TPS already holds `tps`; both are sections of Turun Palloseura.
        club("tps-salibandy", "TPS Salibandy", FLOORBALL, "FIN", "f-liiga" to "687"),
        club("westend-indians", "Westend Indians", FLOORBALL, "FIN", "f-liiga" to "757"),

        // ── CHL-only clubs (their domestic leagues are not in OpenScore yet) ─────────────
        club("bili-tygri-liberec", "Bílí Tygři Liberec", HOCKEY, "CZE", "chl" to "865ec7e2959da256a2a97a8b"),
        club("bordeaux-boxers", "Boxers de Bordeaux", HOCKEY, "FRA", "chl" to "50e896abe7f9760028ebd0c3"),
        club("davos", "HC Davos", HOCKEY, "SUI", "chl" to "fc04d1152903083968962750"),
        club("dynamo-pardubice", "Dynamo Pardubice", HOCKEY, "CZE", "chl" to "3e2b15fb0e41329efc1f6237"),
        club("fribourg-gotteron", "Fribourg-Gottéron", HOCKEY, "SUI", "chl" to "81d5f7bf950746f44e2b92f3"),
        club("geneve-servette", "Genève-Servette", HOCKEY, "SUI", "chl" to "e407e3c30bba319774cc4bea"),
        club("gks-tychy", "GKS Tychy", HOCKEY, "POL", "chl" to "a834198f57003fefc78152e6"),
        club("graz99ers", "Graz99ers", HOCKEY, "AUT", "chl" to "93b3b3514079478af9986663"),
        club("herning-blue-fox", "Herning Blue Fox", HOCKEY, "DEN", "chl" to "ef112cb0eed346d32a775fac"),
        club("kac", "KAC", HOCKEY, "AUT", "chl" to "954f0696fef5e714282a6d75"),
        club("nitra", "HK Nitra", HOCKEY, "SVK", "chl" to "11df2073083f06cccbb5132e"),
        club("plzen", "HC Plzeň", HOCKEY, "CZE", "chl" to "77148013ae31c768167a5d28"),
        club("red-bull-salzburg", "Red Bull Salzburg", HOCKEY, "AUT", "chl" to "aa8d051910780a557dc4a37f"),
        club("storhamar", "Storhamar", HOCKEY, "NOR", "chl" to "e5e5ff0d908f9cc719344e3e"),

        // ── Premier League (UEFA ids for this season's European entrants; `efl` ids for the Carabao Cup) ──
        club("arsenal", "Arsenal", FOOTBALL, "ENG", "premier-league" to "3", "efl" to "t3", "ucl" to "52280"),
        club("aston-villa", "Aston Villa", FOOTBALL, "ENG", "premier-league" to "7", "efl" to "t7", "ucl" to "52683"),
        club("bournemouth", "Bournemouth", FOOTBALL, "ENG", "premier-league" to "91", "efl" to "t91", "ucl" to "2601124"),
        club("brentford", "Brentford", FOOTBALL, "ENG", "premier-league" to "94", "efl" to "t94"),
        club("brighton", "Brighton & Hove Albion", FOOTBALL, "ENG", "premier-league" to "36", "efl" to "t36", "ucl" to "2601105"),
        club("chelsea", "Chelsea", FOOTBALL, "ENG", "premier-league" to "8", "efl" to "t8"),
        club("coventry-city", "Coventry City", FOOTBALL, "ENG", "premier-league" to "9", "efl" to "t9"),
        club("crystal-palace", "Crystal Palace", FOOTBALL, "ENG", "premier-league" to "31", "efl" to "t31", "ucl" to "52916"),
        club("everton", "Everton", FOOTBALL, "ENG", "premier-league" to "11", "efl" to "t11"),
        club("fulham", "Fulham", FOOTBALL, "ENG", "premier-league" to "54", "efl" to "t54"),
        club("hull-city", "Hull City", FOOTBALL, "ENG", "premier-league" to "88", "efl" to "t88"),
        club("ipswich-town", "Ipswich Town", FOOTBALL, "ENG", "premier-league" to "40", "efl" to "t40"),
        club("leeds-united", "Leeds United", FOOTBALL, "ENG", "premier-league" to "2", "efl" to "t2"),
        club("liverpool", "Liverpool", FOOTBALL, "ENG", "premier-league" to "14", "efl" to "t14", "ucl" to "7889"),
        club("manchester-city", "Manchester City", FOOTBALL, "ENG", "premier-league" to "43", "efl" to "t43", "ucl" to "52919"),
        club("manchester-united", "Manchester United", FOOTBALL, "ENG", "premier-league" to "1", "efl" to "t1", "ucl" to "52682"),
        club("newcastle-united", "Newcastle United", FOOTBALL, "ENG", "premier-league" to "4", "efl" to "t4"),
        club("nottingham-forest", "Nottingham Forest", FOOTBALL, "ENG", "premier-league" to "17", "efl" to "t17"),
        club("sunderland", "Sunderland", FOOTBALL, "ENG", "premier-league" to "56", "efl" to "t56", "ucl" to "53360"),
        club("tottenham-hotspur", "Tottenham Hotspur", FOOTBALL, "ENG", "premier-league" to "6", "efl" to "t6"),

        // ── Championship (EFL ids, shared with the Carabao Cup) ─────────────────────────
        club("birmingham-city", "Birmingham City", FOOTBALL, "ENG", "efl" to "t41"),
        club("blackburn-rovers", "Blackburn Rovers", FOOTBALL, "ENG", "efl" to "t5"),
        club("bolton-wanderers", "Bolton Wanderers", FOOTBALL, "ENG", "efl" to "t30"),
        club("bristol-city", "Bristol City", FOOTBALL, "ENG", "efl" to "t113"),
        club("burnley", "Burnley", FOOTBALL, "ENG", "efl" to "t90"),
        club("cardiff-city", "Cardiff City", FOOTBALL, "WAL", "efl" to "t97"),
        club("charlton-athletic", "Charlton Athletic", FOOTBALL, "ENG", "efl" to "t33"),
        club("derby-county", "Derby County", FOOTBALL, "ENG", "efl" to "t24"),
        club("lincoln-city", "Lincoln City", FOOTBALL, "ENG", "efl" to "t83"),
        club("middlesbrough", "Middlesbrough", FOOTBALL, "ENG", "efl" to "t25"),
        club("millwall", "Millwall", FOOTBALL, "ENG", "efl" to "t103"),
        club("norwich-city", "Norwich City", FOOTBALL, "ENG", "efl" to "t45"),
        club("portsmouth", "Portsmouth", FOOTBALL, "ENG", "efl" to "t47"),
        club("preston-north-end", "Preston North End", FOOTBALL, "ENG", "efl" to "t107"),
        club("queens-park-rangers", "Queens Park Rangers", FOOTBALL, "ENG", "efl" to "t52"),
        club("sheffield-united", "Sheffield United", FOOTBALL, "ENG", "efl" to "t49"),
        club("southampton", "Southampton", FOOTBALL, "ENG", "efl" to "t20"),
        club("stoke-city", "Stoke City", FOOTBALL, "ENG", "efl" to "t110"),
        club("swansea-city", "Swansea City", FOOTBALL, "WAL", "efl" to "t80"),
        club("watford", "Watford", FOOTBALL, "ENG", "efl" to "t57"),
        club("west-bromwich-albion", "West Bromwich Albion", FOOTBALL, "ENG", "efl" to "t35"),
        club("west-ham-united", "West Ham United", FOOTBALL, "ENG", "efl" to "t21"),
        club("wolverhampton-wanderers", "Wolverhampton Wanderers", FOOTBALL, "ENG", "efl" to "t39"),
        club("wrexham", "Wrexham", FOOTBALL, "WAL", "efl" to "t109"),

        // ── LaLiga ───────────────────────────────────────────────────────────────────────
        club("alaves", "Deportivo Alavés", FOOTBALL, "ESP", "la-liga" to "d-alaves"),
        club("athletic-club", "Athletic Club", FOOTBALL, "ESP", "la-liga" to "athletic-club"),
        club("atletico-madrid", "Atlético de Madrid", FOOTBALL, "ESP", "la-liga" to "atletico-de-madrid", "ucl" to "50124"),
        club("barcelona", "FC Barcelona", FOOTBALL, "ESP", "la-liga" to "fc-barcelona", "ucl" to "50080"),
        club("celta-vigo", "Celta de Vigo", FOOTBALL, "ESP", "la-liga" to "rc-celta", "ucl" to "53043"),
        club("deportivo-la-coruna", "Deportivo de La Coruña", FOOTBALL, "ESP", "la-liga" to "rc-deportivo"),
        club("elche", "Elche", FOOTBALL, "ESP", "la-liga" to "elche-c-f"),
        club("espanyol", "Espanyol", FOOTBALL, "ESP", "la-liga" to "rcd-espanyol"),
        club("getafe", "Getafe", FOOTBALL, "ESP", "la-liga" to "getafe-cf", "ucl" to "87960"),
        club("levante", "Levante", FOOTBALL, "ESP", "la-liga" to "levante-ud"),
        club("malaga", "Málaga", FOOTBALL, "ESP", "la-liga" to "malaga-cf"),
        club("osasuna", "Osasuna", FOOTBALL, "ESP", "la-liga" to "c-a-osasuna"),
        club("racing-santander", "Racing de Santander", FOOTBALL, "ESP", "la-liga" to "r-racing-club"),
        club("rayo-vallecano", "Rayo Vallecano", FOOTBALL, "ESP", "la-liga" to "rayo-vallecano"),
        club("real-betis", "Real Betis", FOOTBALL, "ESP", "la-liga" to "real-betis", "ucl" to "52265"),
        club("real-madrid", "Real Madrid", FOOTBALL, "ESP", "la-liga" to "real-madrid", "ucl" to "50051"),
        club("real-sociedad", "Real Sociedad", FOOTBALL, "ESP", "la-liga" to "real-sociedad", "ucl" to "50123"),
        club("sevilla", "Sevilla", FOOTBALL, "ESP", "la-liga" to "sevilla-fc"),
        club("valencia", "Valencia", FOOTBALL, "ESP", "la-liga" to "valencia-cf"),
        club("villarreal", "Villarreal", FOOTBALL, "ESP", "la-liga" to "villarreal-cf", "ucl" to "70691"),

        // ── Serie A ──────────────────────────────────────────────────────────────────────
        club("atalanta", "Atalanta", FOOTBALL, "ITA", "serie-a" to "serie-a::Football_Team::b5846a2413804c2e8cab8b773b18370a", "ucl" to "52816"),
        club("bologna", "Bologna", FOOTBALL, "ITA", "serie-a" to "serie-a::Football_Team::4af71b35aab34ad5a7d06148abe66ad6"),
        club("cagliari", "Cagliari", FOOTBALL, "ITA", "serie-a" to "serie-a::Football_Team::25aecd0eda3e4453aabd9a9d5e7fba0d"),
        club("como", "Como", FOOTBALL, "ITA", "serie-a" to "serie-a::Football_Team::367e70bf50b346209f8a0f16429850cb", "ucl" to "79946"),
        club("fiorentina", "Fiorentina", FOOTBALL, "ITA", "serie-a" to "serie-a::Football_Team::5bce12d5bd864c2297695d970f92576d"),
        club("frosinone", "Frosinone", FOOTBALL, "ITA", "serie-a" to "serie-a::Football_Team::b283fcc0aeda401bb081fcd764e290db"),
        club("genoa", "Genoa", FOOTBALL, "ITA", "serie-a" to "serie-a::Football_Team::8c7aa94d22f44738951748e2ccdf319a"),
        club("inter", "Inter", FOOTBALL, "ITA", "serie-a" to "serie-a::Football_Team::b7421caff23448c49134fa4f9095ee09", "ucl" to "50138"),
        club("juventus", "Juventus", FOOTBALL, "ITA", "serie-a" to "serie-a::Football_Team::0ae9210dce6f4f9b9d50aeeb19b0d371", "ucl" to "50139", "espn" to "111"),
        club("lazio", "Lazio", FOOTBALL, "ITA", "serie-a" to "serie-a::Football_Team::fe6490f2b16e45be9956a1cd04aaf3a2"),
        club("lecce", "Lecce", FOOTBALL, "ITA", "serie-a" to "serie-a::Football_Team::ced7bf0df3a140dfa48138311122133b"),
        club("milan", "Milan", FOOTBALL, "ITA", "serie-a" to "serie-a::Football_Team::d0867ddf777c41789ca282b8276002b0", "ucl" to "50058"),
        club("monza", "Monza", FOOTBALL, "ITA", "serie-a" to "serie-a::Football_Team::9ba470f39580450fac7654956ba574fa"),
        club("napoli", "Napoli", FOOTBALL, "ITA", "serie-a" to "serie-a::Football_Team::f791dab8f0e4449e9884dd8dbd42dbcc", "ucl" to "50136"),
        club("parma", "Parma", FOOTBALL, "ITA", "serie-a" to "serie-a::Football_Team::3294993c79b14d918ccdc78da0fb90c5"),
        club("roma", "Roma", FOOTBALL, "ITA", "serie-a" to "serie-a::Football_Team::8ddc09c1aa73448da2dff953edd95d82", "ucl" to "50137"),
        club("sassuolo", "Sassuolo", FOOTBALL, "ITA", "serie-a" to "serie-a::Football_Team::b70390ba4e3c4bc2947a37617d53e8a3"),
        club("torino", "Torino", FOOTBALL, "ITA", "serie-a" to "serie-a::Football_Team::a55dcc2058e94976b572262fc564a74c"),
        club("udinese", "Udinese", FOOTBALL, "ITA", "serie-a" to "serie-a::Football_Team::630b1e3631db42498d1b7bc94595c5e0"),
        club("venezia", "Venezia", FOOTBALL, "ITA", "serie-a" to "serie-a::Football_Team::a28236708d214df3a2e2e04ceb7e5c54"),

        // ── Bundesliga ───────────────────────────────────────────────────────────────────
        club("augsburg", "FC Augsburg", FOOTBALL, "GER", "bundesliga" to "DFL-CLU-000010", "espn" to "3841"),
        club("bayer-leverkusen", "Bayer 04 Leverkusen", FOOTBALL, "GER", "bundesliga" to "DFL-CLU-00000B", "ucl" to "50109", "espn" to "131"),
        club("bayern-munchen", "FC Bayern München", FOOTBALL, "GER", "bundesliga" to "DFL-CLU-00000G", "ucl" to "50037", "espn" to "132"),
        club("borussia-dortmund", "Borussia Dortmund", FOOTBALL, "GER", "bundesliga" to "DFL-CLU-000007", "ucl" to "52758", "espn" to "124"),
        club("borussia-monchengladbach", "Borussia Mönchengladbach", FOOTBALL, "GER", "bundesliga" to "DFL-CLU-000004", "espn" to "268"),
        club("eintracht-frankfurt", "Eintracht Frankfurt", FOOTBALL, "GER", "bundesliga" to "DFL-CLU-00000F", "espn" to "125"),
        club("elversberg", "SV Elversberg", FOOTBALL, "GER", "bundesliga" to "DFL-CLU-000N6L", "espn" to "10388"),
        club("freiburg", "SC Freiburg", FOOTBALL, "GER", "bundesliga" to "DFL-CLU-00000A", "ucl" to "59880", "espn" to "126"),
        club("hamburger-sv", "Hamburger SV", FOOTBALL, "GER", "bundesliga" to "DFL-CLU-00000C", "espn" to "127"),
        club("hoffenheim", "TSG Hoffenheim", FOOTBALL, "GER", "bundesliga" to "DFL-CLU-000002", "ucl" to "2600431", "espn" to "7911"),
        club("koln", "1. FC Köln", FOOTBALL, "GER", "bundesliga" to "DFL-CLU-000008", "espn" to "122"),
        club("mainz", "1. FSV Mainz 05", FOOTBALL, "GER", "bundesliga" to "DFL-CLU-000006", "espn" to "2950"),
        club("paderborn", "SC Paderborn 07", FOOTBALL, "GER", "bundesliga" to "DFL-CLU-00000L", "espn" to "3307"),
        club("rb-leipzig", "RB Leipzig", FOOTBALL, "GER", "bundesliga" to "DFL-CLU-000017", "ucl" to "2603790", "espn" to "11420"),
        club("schalke", "FC Schalke 04", FOOTBALL, "GER", "bundesliga" to "DFL-CLU-000009", "espn" to "133"),
        club("stuttgart", "VfB Stuttgart", FOOTBALL, "GER", "bundesliga" to "DFL-CLU-00000D", "ucl" to "50107", "espn" to "134"),
        club("union-berlin", "1. FC Union Berlin", FOOTBALL, "GER", "bundesliga" to "DFL-CLU-00000V", "espn" to "598"),
        club("werder-bremen", "SV Werder Bremen", FOOTBALL, "GER", "bundesliga" to "DFL-CLU-00000E", "espn" to "137"),

        // ── Ligue 1 ──────────────────────────────────────────────────────────────────────
        club("angers", "Angers SCO", FOOTBALL, "FRA", "ligue1" to "l1_championship_club_2026_37"),
        club("auxerre", "AJ Auxerre", FOOTBALL, "FRA", "ligue1" to "l1_championship_club_2026_2"),
        club("brest", "Stade Brestois 29", FOOTBALL, "FRA", "ligue1" to "l1_championship_club_2026_44"),
        club("le-havre", "Le Havre AC", FOOTBALL, "FRA", "ligue1" to "l1_championship_club_2026_5"),
        club("le-mans", "Le Mans FC", FOOTBALL, "FRA", "ligue1" to "l1_championship_club_2026_26"),
        club("lens", "RC Lens", FOOTBALL, "FRA", "ligue1" to "l1_championship_club_2026_6", "ucl" to "52277"),
        club("lille", "LOSC Lille", FOOTBALL, "FRA", "ligue1" to "l1_championship_club_2026_158", "ucl" to "75797"),
        club("lorient", "FC Lorient", FOOTBALL, "FRA", "ligue1" to "l1_championship_club_2026_7"),
        club("lyon", "Olympique Lyonnais", FOOTBALL, "FRA", "ligue1" to "l1_championship_club_2026_159", "ucl" to "5312"),
        club("marseille", "Olympique de Marseille", FOOTBALL, "FRA", "ligue1" to "l1_championship_club_2026_1", "ucl" to "52748"),
        club("monaco", "AS Monaco", FOOTBALL, "FRA", "ligue1" to "l1_championship_club_2026_9", "ucl" to "50023"),
        club("nice", "OGC Nice", FOOTBALL, "FRA", "ligue1" to "l1_championship_club_2026_30"),
        club("paris-fc", "Paris FC", FOOTBALL, "FRA", "ligue1" to "l1_championship_club_2026_90"),
        club("paris-saint-germain", "Paris Saint-Germain", FOOTBALL, "FRA", "ligue1" to "l1_championship_club_2026_13", "ucl" to "52747", "espn" to "160"),
        club("rennes", "Stade Rennais", FOOTBALL, "FRA", "ligue1" to "l1_championship_club_2026_14", "ucl" to "55031"),
        club("strasbourg", "RC Strasbourg Alsace", FOOTBALL, "FRA", "ligue1" to "l1_championship_club_2026_15"),
        club("toulouse", "Toulouse FC", FOOTBALL, "FRA", "ligue1" to "l1_championship_club_2026_16"),
        club("troyes", "ESTAC Troyes", FOOTBALL, "FRA", "ligue1" to "l1_championship_club_2026_33"),

        // ── Malta Premier League ─────────────────────────────────────────────────────────
        club("balzan", "Balzan", FOOTBALL, "MLT", "malta-premier" to "39612"),
        club("birkirkara", "Birkirkara", FOOTBALL, "MLT", "malta-premier" to "39636"),
        club("birzebbuga-st-peters", "Birżebbuġa St. Peter's", FOOTBALL, "MLT", "malta-premier" to "40417"),
        club("floriana", "Floriana", FOOTBALL, "MLT", "malta-premier" to "39637"),
        club("gzira-united", "Gżira United", FOOTBALL, "MLT", "malta-premier" to "39615"),
        club("hamrun-spartans", "Ħamrun Spartans", FOOTBALL, "MLT", "malta-premier" to "39639"),
        club("hibernians", "Hibernians", FOOTBALL, "MLT", "malta-premier" to "39640"),
        club("marsaxlokk", "Marsaxlokk", FOOTBALL, "MLT", "malta-premier" to "39617"),
        club("mosta", "Mosta", FOOTBALL, "MLT", "malta-premier" to "39606"),
        club("sliema-wanderers", "Sliema Wanderers", FOOTBALL, "MLT", "malta-premier" to "39646"),
        club("valletta", "Valletta", FOOTBALL, "MLT", "malta-premier" to "39648"),
        club("zabbar-st-patrick", "Żabbar St. Patrick", FOOTBALL, "MLT", "malta-premier" to "40419"),

        // ── Allsvenskan / Superettan (one Sportomedia id space) + Fogis (every SvFF competition) ──
        club("aik", "AIK", FOOTBALL, "SWE", "sportomedia" to "AIK", "fogis" to "66036"),
        club("brommapojkarna", "IF Brommapojkarna", FOOTBALL, "SWE", "sportomedia" to "IFBP", "fogis" to "25591"),
        club("degerfors", "Degerfors IF", FOOTBALL, "SWE", "sportomedia" to "DEIF", "fogis" to "25640"),
        club("djurgarden", "Djurgårdens IF", FOOTBALL, "SWE", "sportomedia" to "DIF", "fogis" to "89483"),
        club("elfsborg", "IF Elfsborg", FOOTBALL, "SWE", "sportomedia" to "IFE", "fogis" to "25504"),
        club("gais", "GAIS", FOOTBALL, "SWE", "sportomedia" to "GAIS", "fogis" to "25530"),
        club("hacken", "BK Häcken", FOOTBALL, "SWE", "sportomedia" to "BKH", "fogis" to "25509"),
        club("halmstad", "Halmstads BK", FOOTBALL, "SWE", "sportomedia" to "HBK", "fogis" to "200265"),
        club("hammarby", "Hammarby IF", FOOTBALL, "SWE", "sportomedia" to "HAM", "fogis" to "66592"),
        club("ifk-goteborg", "IFK Göteborg", FOOTBALL, "SWE", "sportomedia" to "GBG", "fogis" to "25508"),
        club("kalmar-ff", "Kalmar FF", FOOTBALL, "SWE", "sportomedia" to "KFF", "fogis" to "25521"),
        club("malmo-ff", "Malmö FF", FOOTBALL, "SWE", "sportomedia" to "MFF", "fogis" to "25517"),
        club("mjallby", "Mjällby AIF", FOOTBALL, "SWE", "sportomedia" to "MAIF", "fogis" to "25506", "ucl" to "74233"),
        club("orgryte", "Örgryte IS", FOOTBALL, "SWE", "sportomedia" to "OIS", "fogis" to "204429"),
        club("sirius", "IK Sirius", FOOTBALL, "SWE", "sportomedia" to "IKS", "fogis" to "108445"),
        club("vasteras-sk", "Västerås SK", FOOTBALL, "SWE", "sportomedia" to "VSK", "fogis" to "25525"),
        club("brage", "IK Brage", FOOTBALL, "SWE", "sportomedia" to "IKB", "fogis" to "25507"),
        club("falkenberg", "Falkenbergs FF", FOOTBALL, "SWE", "sportomedia" to "FFF", "fogis" to "25686"),
        club("gif-sundsvall", "GIF Sundsvall", FOOTBALL, "SWE", "sportomedia" to "SUN", "fogis" to "25513"),
        club("helsingborg", "Helsingborgs IF", FOOTBALL, "SWE", "sportomedia" to "HIF", "fogis" to "25511"),
        club("ifk-norrkoping", "IFK Norrköping", FOOTBALL, "SWE", "sportomedia" to "NOR", "fogis" to "26935"),
        club("landskrona", "Landskrona BoIS", FOOTBALL, "SWE", "sportomedia" to "LAN", "fogis" to "25522"),
        club("ljungskile", "Ljungskile SK", FOOTBALL, "SWE", "sportomedia" to "LJUN", "fogis" to "245789"),
        club("nordic-united", "Nordic United FC", FOOTBALL, "SWE", "sportomedia" to "NFC", "fogis" to "146841"),
        club("norrby", "Norrby IF", FOOTBALL, "SWE", "sportomedia" to "NIF", "fogis" to "25683"),
        club("oddevold", "IK Oddevold", FOOTBALL, "SWE", "sportomedia" to "IKO", "fogis" to "25552"),
        club("orebro-sk", "Örebro SK", FOOTBALL, "SWE", "sportomedia" to "OSK", "fogis" to "89484"),
        club("oster", "Östers IF", FOOTBALL, "SWE", "sportomedia" to "OIF", "fogis" to "25526"),
        club("ostersund", "Östersunds FK", FOOTBALL, "SWE", "sportomedia" to "OFK", "fogis" to "214472"),
        club("sandviken", "Sandvikens IF", FOOTBALL, "SWE", "sportomedia" to "SANDIF", "fogis" to "25595"),
        club("varberg", "Varbergs BoIS", FOOTBALL, "SWE", "sportomedia" to "VAR", "fogis" to "26111"),
        club("varnamo", "IFK Värnamo", FOOTBALL, "SWE", "sportomedia" to "VARN", "fogis" to "25590"),

        // ── MLS (stats-api club ids; the feed calls Canada's three clubs "US" — the flag here is the club's country) ──
        club("atlanta-united", "Atlanta United", FOOTBALL, "USA", "mls" to "MLS-CLU-00000A"),
        club("austin", "Austin FC", FOOTBALL, "USA", "mls" to "MLS-CLU-000003"),
        club("cf-montreal", "CF Montréal", FOOTBALL, "CAN", "mls" to "MLS-CLU-000006"),
        club("charlotte", "Charlotte FC", FOOTBALL, "USA", "mls" to "MLS-CLU-00000I"),
        club("chicago-fire", "Chicago Fire FC", FOOTBALL, "USA", "mls" to "MLS-CLU-00000F"),
        club("colorado-rapids", "Colorado Rapids", FOOTBALL, "USA", "mls" to "MLS-CLU-00000J"),
        club("columbus-crew", "Columbus Crew", FOOTBALL, "USA", "mls" to "MLS-CLU-00000E"),
        club("dc-united", "D.C. United", FOOTBALL, "USA", "mls" to "MLS-CLU-00000D"),
        club("fc-cincinnati", "FC Cincinnati", FOOTBALL, "USA", "mls" to "MLS-CLU-000007"),
        club("fc-dallas", "FC Dallas", FOOTBALL, "USA", "mls" to "MLS-CLU-000005"),
        club("houston-dynamo", "Houston Dynamo FC", FOOTBALL, "USA", "mls" to "MLS-CLU-00000H"),
        club("inter-miami", "Inter Miami CF", FOOTBALL, "USA", "mls" to "MLS-CLU-000008"),
        club("la-galaxy", "LA Galaxy", FOOTBALL, "USA", "mls" to "MLS-CLU-00000G"),
        club("lafc", "Los Angeles Football Club", FOOTBALL, "USA", "mls" to "MLS-CLU-000001"),
        club("minnesota-united", "Minnesota United FC", FOOTBALL, "USA", "mls" to "MLS-CLU-00000L"),
        club("nashville", "Nashville SC", FOOTBALL, "USA", "mls" to "MLS-CLU-000009"),
        club("new-england-revolution", "New England Revolution", FOOTBALL, "USA", "mls" to "MLS-CLU-00000N"),
        club("new-york-city", "New York City FC", FOOTBALL, "USA", "mls" to "MLS-CLU-000004"),
        club("new-york-red-bulls", "New York Red Bulls", FOOTBALL, "USA", "mls" to "MLS-CLU-00000B"),
        club("orlando-city", "Orlando City", FOOTBALL, "USA", "mls" to "MLS-CLU-00000O"),
        club("philadelphia-union", "Philadelphia Union", FOOTBALL, "USA", "mls" to "MLS-CLU-000002"),
        club("portland-timbers", "Portland Timbers", FOOTBALL, "USA", "mls" to "MLS-CLU-00000P"),
        club("real-salt-lake", "Real Salt Lake", FOOTBALL, "USA", "mls" to "MLS-CLU-00000R"),
        club("san-diego", "San Diego FC", FOOTBALL, "USA", "mls" to "MLS-CLU-000065"),
        club("san-jose-earthquakes", "San Jose Earthquakes", FOOTBALL, "USA", "mls" to "MLS-CLU-00000Q"),
        club("seattle-sounders", "Seattle Sounders FC", FOOTBALL, "USA", "mls" to "MLS-CLU-00000S"),
        club("sporting-kansas-city", "Sporting Kansas City", FOOTBALL, "USA", "mls" to "MLS-CLU-00000K"),
        club("st-louis-city", "St. Louis CITY SC", FOOTBALL, "USA", "mls" to "MLS-CLU-00001L"),
        club("toronto", "Toronto FC", FOOTBALL, "CAN", "mls" to "MLS-CLU-00000M"),
        club("vancouver-whitecaps", "Vancouver Whitecaps FC", FOOTBALL, "CAN", "mls" to "MLS-CLU-00000C"),

        // ── UEFA-only clubs (their domestic leagues are not in OpenScore yet) ────────────
        club("aarhus", "AGF Aarhus", FOOTBALL, "DEN", "ucl" to "50019", "espn" to "7853"),
        club("aek-athens", "AEK Athens", FOOTBALL, "GRE", "ucl" to "50129", "espn" to "887"),
        club("ajax", "Ajax", FOOTBALL, "NED", "ucl" to "50143", "espn" to "139"),
        club("anderlecht", "Anderlecht", FOOTBALL, "BEL", "ucl" to "50074", "espn" to "441"),
        club("ararat-armenia", "Ararat-Armenia", FOOTBALL, "ARM", "ucl" to "2610304", "espn" to "20024"),
        club("az-alkmaar", "AZ Alkmaar", FOOTBALL, "NED", "ucl" to "52327", "espn" to "140"),
        club("benfica", "Benfica", FOOTBALL, "POR", "ucl" to "50147", "espn" to "1929"),
        club("besiktas", "Beşiktaş", FOOTBALL, "TUR", "ucl" to "50157", "espn" to "1895"),
        club("bodo-glimt", "Bodø/Glimt", FOOTBALL, "NOR", "ucl" to "59333", "espn" to "2980"),
        club("borac-banja-luka", "Borac Banja Luka", FOOTBALL, "BIH", "ucl" to "50104", "espn" to "20710"),
        club("braga", "Braga", FOOTBALL, "POR", "ucl" to "52336", "espn" to "2994"),
        club("brann", "Brann", FOOTBALL, "NOR", "ucl" to "52770", "espn" to "620"),
        club("celje", "Celje", FOOTBALL, "SVN", "ucl" to "59030", "espn" to "3362"),
        club("celtic", "Celtic", FOOTBALL, "SCO", "ucl" to "50050", "espn" to "256"),
        club("club-brugge", "Club Brugge", FOOTBALL, "BEL", "ucl" to "50043", "espn" to "570"),
        club("copenhagen", "FC Copenhagen", FOOTBALL, "DEN", "ucl" to "52709", "espn" to "909"),
        club("crvena-zvezda", "Crvena Zvezda", FOOTBALL, "SRB", "ucl" to "50069", "espn" to "2290"),
        club("cska-sofia", "CSKA Sofia", FOOTBALL, "BUL", "ucl" to "2608297", "espn" to "10834"),
        club("dinamo-zagreb", "Dinamo Zagreb", FOOTBALL, "CRO", "ucl" to "50164", "espn" to "597"),
        club("egnatia", "Egnatia", FOOTBALL, "ALB", "ucl" to "88148", "espn" to "21943"),
        club("fenerbahce", "Fenerbahçe", FOOTBALL, "TUR", "ucl" to "52692", "espn" to "436"),
        club("ferencvaros", "Ferencváros", FOOTBALL, "HUN", "ucl" to "52298", "espn" to "622"),
        club("feyenoord", "Feyenoord", FOOTBALL, "NED", "ucl" to "52749", "espn" to "142"),
        club("galatasaray", "Galatasaray", FOOTBALL, "TUR", "ucl" to "50067", "espn" to "432"),
        club("gent", "Gent", FOOTBALL, "BEL", "ucl" to "4608", "espn" to "3611"),
        club("hajduk-split", "Hajduk Split", FOOTBALL, "CRO", "ucl" to "52359", "espn" to "489"),
        club("hapoel-beer-sheva", "Hapoel Be'er Sheva", FOOTBALL, "ISR", "ucl" to "59340", "espn" to "13083"),
        club("hearts", "Heart of Midlothian", FOOTBALL, "SCO", "ucl" to "50120", "espn" to "262"),
        club("iberia-tbilisi", "Iberia 1999 Tbilisi", FOOTBALL, "GEO", "ucl" to "2605905", "espn" to "20025"),
        club("inter-escaldes", "Inter Club d'Escaldes", FOOTBALL, "AND", "ucl" to "63401", "espn" to "20703"),
        club("jablonec", "Jablonec", FOOTBALL, "CZE", "ucl" to "62169", "espn" to "7922"),
        club("jagiellonia", "Jagiellonia Białystok", FOOTBALL, "POL", "ucl" to "2600277", "espn" to "11505"),
        club("kairat", "Kairat Almaty", FOOTBALL, "KAZ", "ucl" to "79970", "espn" to "2528"),
        club("kauno-zalgiris", "Kauno Žalgiris", FOOTBALL, "LTU", "ucl" to "2605907", "espn" to "20028"),
        club("kups", "KuPS Kuopio", FOOTBALL, "FIN", "ucl" to "52350", "espn" to "8169"),
        club("lask", "LASK", FOOTBALL, "AUT", "ucl" to "63405", "espn" to "4411"),
        club("lech-poznan", "Lech Poznań", FOOTBALL, "POL", "ucl" to "64227", "espn" to "2990"),
        club("levski-sofia", "Levski Sofia", FOOTBALL, "BUL", "ucl" to "50044", "espn" to "490"),
        club("lillestrom", "Lillestrøm", FOOTBALL, "NOR", "ucl" to "52314", "espn" to "987"),
        club("lincoln-red-imps", "Lincoln Red Imps", FOOTBALL, "GIB", "ucl" to "2605572", "espn" to "17856"),
        club("lugano", "Lugano", FOOTBALL, "SUI", "ucl" to "8538", "espn" to "7672"),
        club("midtjylland", "Midtjylland", FOOTBALL, "DEN", "ucl" to "75795", "espn" to "572"),
        club("nec-nijmegen", "NEC Nijmegen", FOOTBALL, "NED", "ucl" to "52330", "espn" to "147"),
        club("nordsjaelland", "Nordsjælland", FOOTBALL, "DEN", "ucl" to "79940", "espn" to "3101"),
        club("ofi-crete", "OFI Crete", FOOTBALL, "GRE", "ucl" to "52953", "espn" to "1010"),
        club("olympiacos", "Olympiacos", FOOTBALL, "GRE", "ucl" to "2610", "espn" to "435"),
        club("omonia", "Omonia", FOOTBALL, "CYP", "ucl" to "50077", "espn" to "617"),
        club("pafos", "Pafos", FOOTBALL, "CYP", "ucl" to "2609532", "espn" to "22281"),
        club("panathinaikos", "Panathinaikos", FOOTBALL, "GRE", "ucl" to "50084", "espn" to "443"),
        club("porto", "Porto", FOOTBALL, "POR", "ucl" to "50064", "espn" to "437"),
        club("psv", "PSV Eindhoven", FOOTBALL, "NED", "ucl" to "50062", "espn" to "148"),
        club("riga", "Riga FC", FOOTBALL, "LVA", "ucl" to "2607924", "espn" to "19246"),
        club("sabah", "Sabah", FOOTBALL, "AZE", "ucl" to "2609356", "espn" to "21922"),
        club("salzburg", "Red Bull Salzburg", FOOTBALL, "AUT", "ucl" to "50030", "espn" to "2790"),
        club("shakhtar-donetsk", "Shakhtar Donetsk", FOOTBALL, "UKR", "ucl" to "52707", "espn" to "493"),
        club("sint-truiden", "Sint-Truiden", FOOTBALL, "BEL", "ucl" to "52883", "espn" to "936"),
        club("slavia-praha", "Slavia Praha", FOOTBALL, "CZE", "ucl" to "52498", "espn" to "494"),
        club("slovan-bratislava", "Slovan Bratislava", FOOTBALL, "SVK", "ucl" to "52797", "espn" to "521"),
        club("sparta-praha", "Sparta Praha", FOOTBALL, "CZE", "ucl" to "50033", "espn" to "433"),
        club("sporting-cp", "Sporting CP", FOOTBALL, "POR", "ucl" to "50149", "espn" to "2250"),
        club("sturm-graz", "Sturm Graz", FOOTBALL, "AUT", "ucl" to "50111", "espn" to "3746"),
        club("thun", "Thun", FOOTBALL, "SUI", "ucl" to "80409", "espn" to "3024"),
        club("torreense", "Torreense", FOOTBALL, "POR", "ucl" to "2603107", "espn" to "21615"),
        club("trabzonspor", "Trabzonspor", FOOTBALL, "TUR", "ucl" to "52731", "espn" to "997"),
        club("twente", "Twente", FOOTBALL, "NED", "ucl" to "52818", "espn" to "152"),
        club("union-saint-gilloise", "Union Saint-Gilloise", FOOTBALL, "BEL", "ucl" to "64125", "espn" to "5807"),
        club("universitatea-craiova", "Universitatea Craiova", FOOTBALL, "ROU", "ucl" to "2606501", "espn" to "8089"),
        club("viking", "Viking", FOOTBALL, "NOR", "ucl" to "52319", "espn" to "510"),
        club("viktoria-plzen", "Viktoria Plzeň", FOOTBALL, "CZE", "ucl" to "64388", "espn" to "11706"),

        // ── MLB ──────────────────────────────────────────────────────────────────────────
        club("arizona-diamondbacks", "Arizona Diamondbacks", BASEBALL, "USA", "mlb" to "109"),
        club("athletics", "Athletics", BASEBALL, "USA", "mlb" to "133"),
        club("atlanta-braves", "Atlanta Braves", BASEBALL, "USA", "mlb" to "144"),
        club("baltimore-orioles", "Baltimore Orioles", BASEBALL, "USA", "mlb" to "110"),
        club("boston-red-sox", "Boston Red Sox", BASEBALL, "USA", "mlb" to "111"),
        club("chicago-cubs", "Chicago Cubs", BASEBALL, "USA", "mlb" to "112"),
        club("chicago-white-sox", "Chicago White Sox", BASEBALL, "USA", "mlb" to "145"),
        club("cincinnati-reds", "Cincinnati Reds", BASEBALL, "USA", "mlb" to "113"),
        club("cleveland-guardians", "Cleveland Guardians", BASEBALL, "USA", "mlb" to "114"),
        club("colorado-rockies", "Colorado Rockies", BASEBALL, "USA", "mlb" to "115"),
        club("detroit-tigers", "Detroit Tigers", BASEBALL, "USA", "mlb" to "116"),
        club("houston-astros", "Houston Astros", BASEBALL, "USA", "mlb" to "117"),
        club("kansas-city-royals", "Kansas City Royals", BASEBALL, "USA", "mlb" to "118"),
        club("los-angeles-angels", "Los Angeles Angels", BASEBALL, "USA", "mlb" to "108"),
        club("los-angeles-dodgers", "Los Angeles Dodgers", BASEBALL, "USA", "mlb" to "119"),
        club("miami-marlins", "Miami Marlins", BASEBALL, "USA", "mlb" to "146"),
        club("milwaukee-brewers", "Milwaukee Brewers", BASEBALL, "USA", "mlb" to "158"),
        club("minnesota-twins", "Minnesota Twins", BASEBALL, "USA", "mlb" to "142"),
        club("new-york-mets", "New York Mets", BASEBALL, "USA", "mlb" to "121"),
        club("new-york-yankees", "New York Yankees", BASEBALL, "USA", "mlb" to "147"),
        club("philadelphia-phillies", "Philadelphia Phillies", BASEBALL, "USA", "mlb" to "143"),
        club("pittsburgh-pirates", "Pittsburgh Pirates", BASEBALL, "USA", "mlb" to "134"),
        club("san-diego-padres", "San Diego Padres", BASEBALL, "USA", "mlb" to "135"),
        club("san-francisco-giants", "San Francisco Giants", BASEBALL, "USA", "mlb" to "137"),
        club("seattle-mariners", "Seattle Mariners", BASEBALL, "USA", "mlb" to "136"),
        club("st-louis-cardinals", "St. Louis Cardinals", BASEBALL, "USA", "mlb" to "138"),
        club("tampa-bay-rays", "Tampa Bay Rays", BASEBALL, "USA", "mlb" to "139"),
        club("texas-rangers", "Texas Rangers", BASEBALL, "USA", "mlb" to "140"),
        club("toronto-blue-jays", "Toronto Blue Jays", BASEBALL, "CAN", "mlb" to "141"),
        club("washington-nationals", "Washington Nationals", BASEBALL, "USA", "mlb" to "120"),
    )
}
